
 drop table if exists `hy_calculate_probability`;  
 create table `hy_calculate_probability`  ( 
 `id` varchar(255) not null, 
 `device_id` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `injury_type_list` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `effectiveness` int, 
 `inspect_time` int, 
 `corrode_speed` float, 
 `soil_corrode_speed` float, 
 `medium_corrode_speed` float, 
 `service_life` int, 
 `electric_resistivity` float, 
 `foil_type` int, 
 `emission_type` int, 
 `cathode_protected_type` int, 
 `rpb_state` int, 
 `soil_temperature` float, 
 `medium_state` int, 
 `medium_temperature` float, 
 `water_facilities` int, 
 `corrode_type` int, 
 `as_required` int, 
 `sedimentation_situation` int, 
 `thinning_mechanism` int, 
 `locality_thinning` int, 
 `inspection_method` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `external_environment` int, 
 `pipe_offset` int, 
 `pipe_line_complexity` int, 
 `invalid_mechanism` int, 
 `sensibility` int, 
 `brittle_fracture_question` int, 
 `mdmt` float, 
 `isavoid_cold` int, 
 `avoid_cold_temperature` float, 
 `recommend_min_temperature` float, 
 `boiling_point` float, 
 `avoid_knock_temperature` float, 
 `pwht` int, 
 `safe_operation` int, 
 `jfactor` float, 
 `change_temperature` float, 
 `soil_type` int, 
 `fluid_type` int, 
 `hole` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `is_good_contact` int, 
 `hliq` float, 
 `over_coffer_per` float, 
 `over_coffer_per_inarea` float, 
 `over_coffer_per_outarea` float, 
 `sgw` float, 
 `procost` float, 
 `year` int, 
 `dthinf` float, 
 `dextdf` float, 
 `dsccf` float, 
 `dbritf` float, 
 `probability_level` int, 
 `consequence_level` int, 
 `scc` float, 
 `isacceptance` bit, 
 `method` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `next_year` int, 
 `risk_target_value` float, 
 `risk_target_level` int, 
 `component_id` varchar(255) character set utf8 collate utf8_general_ci default null, 
 `history_id` varchar(255) character set utf8 collate utf8_general_ci default null, 
 primary key (`id`) using btree,
 index `id`(`id`) using btree 
 ) engine = innodb character set = utf8 collate = utf8_general_ci;
